<template>
  <v-container fluid grid-list-xl>
    <v-layout wrap align-center>
      <v-flex xs12 d-flex>
        <v-data-table :headers="headers" :items="showed" hide-actions>
          <template slot="card" slot-scope="props">
            <tr @click="open(props.item.DOKNR)">
              <td class="text-xs-left">{{ props.item.DOKNR }}</td>
              <td class="text-xs-left">{{ props.item.NAME_DRVR }}</td>
              <td class="text-xs-left">{{ M(props.item.E_DATE + props.item.E_TIME, 'YYYYMMDDHHmmSS').format('DD.MM.YYYY HH:mm:SS') }}</td>
              <td class="text-xs-left">{{ M(props.item.VALID_DATE_FROM, 'YYYYMMDD').format('DD.MM.YYYY') }}</td>
              <td class="text-xs-left">{{ M(props.item.VALID_DATE_TO, 'YYYYMMDD').format('DD.MM.YYYY') }}</td>
            </tr>
          </template>
        </v-data-table>
      </v-flex>
      <v-flex xs12 d-flex></v-flex>
      <v-flex xs12 d-flex></v-flex>
      <v-flex xs12 d-flex></v-flex>
      <v-flex xs12 d-flex></v-flex>
    </v-layout>
  </v-container>
</template>

<script>
import axios from 'axios'
export default {
  name: 'card',
  data () {
    return {
      headers: [
        { text: 'Отметка', value: '', sortable: false },
        { text: 'Имя инициатора', value: '', sortable: false },
        { text: 'Имя создателя', value: '', sortable: false },
        { text: 'Дата и время создания', value: '', sortable: false }
      ],
      card: [],
      tmp: [{
        RESULT: 'SUCCESS',
        RESULT_TXT: 'SUCCESS',
        RESULT_COLOR: 'GREEN',
        NAME_TEXT: 'Технический Пользователь',
        STATUS: '57',
        DATA_CARD:
          { MANDT: '100',
            DOKAR: '000',
            DOKNR: '0000000000005000000125144',
            DOKVR: '00',
            DOKTL: '000',
            DOCTYPE: '5001',
            DOC_CLASS: '003',
            AUTO_MARKA: '',
            AUTO_NOMER: '',
            PRICEP_MARKA: '',
            PRICEP_NOMER: '',
            ID_CARD_NUMB: '743529',
            NAME_DRVR: 'ДАНИЛОВ А.А.',
            PHONE: '',
            VALID_DATE_FROM: '20181008',
            VALID_DATE_TO: '20181008',
            ZRAZOVIY: 'X',
            ZWAIT_RAZRESH: '',
            ZPROPUSK: '',
            INIT_OID: '50124880',
            INIT_ONM: '1.РУКОВОДСТВО МЕДЕЭЛЕКТРОЛИТНОГО ПРОИЗВО',
            INIT_PID: '11098751',
            INIT_PNM: 'Огорелышев Сергей Владимирович',
            INIT_SID: '00757483',
            INIT_SNM: 'НАЧ-К МЕДЕЭЛЕКТРОЛИТНОГО ПРОИЗ-ВА-НАЧ.ЦЕ',
            INIT_UID: 'OGOREL_SV',
            INIT_UNM: 'Сергей Владимирович Огорелышев',
            AUTHOR_OID: '00747803',
            AUTHOR_ONM: '2.ЦЕХ ЭЛЕКТРОЛИЗА МЕДИ',
            AUTHOR_PID: '11075104',
            AUTHOR_PNM: 'Крижевских Оксана Сергеевна',
            AUTHOR_SID: '00769159',
            AUTHOR_SNM: 'СПЕЦИАЛИСТ ПО КАДРАМ',
            AUTHOR_UID: 'KRIZHEV_OS',
            AUTHOR_UNM: 'Оксана Сергеевна Крижевских',
            ZTRANSP_COMP: '',
            ZWAIT_INI: '',
            ZFULLNAME_TRANSP: '',
            ZDESCR_SMALL: '',
            CREATED_BY: 'KRIZHEV_OS',
            CREATED_ON: '20181005',
            CREATED_TM: '113058',
            CHANGED_BY: 'SUDAKOV_AB',
            CHANGED_ON: '20181005',
            CHANGED_TM: '152156',
            WI_ID: '000000000000',
            DELETE_FLAG: '',
            LOGSYS: 'R3PCLNT100' },
        ES_CARDD:
          { MANDT: '100',
            DOKAR: '000',
            DOKNR: '0000000000005000000125144',
            DOKVR: '00',
            DOKTL: '000',
            CARDNUM: '007105',
            DOKST: '57',
            PREAR: '',
            PRENR: '',
            PREVR: '',
            PRETL: '',
            BARCODE: '' },
        ES_STATUS: { MANDT: '100', DOKST: '57', DOSAR: '' },
        ES_STATUS_T:
          { MANDT: '100',
            DOKST: '57',
            SPRAS: 'R',
            STABK: '57',
            DOSTX: 'Доступ разрешен' },
        OBJECTLINKS: [],
        DOCUMENTFILES: [],
        DESCR_ALV:
          [ { MODE: '',
            DYNPRO: '0000',
            FIELDNAME: 'ZDOK_TAB',
            TABNAME: 'ZDF_ZDOK_007105',
            DDTABNAME: 'ZDF_ZDOK_007105',
            MAX_RECORD: '000000',
            REF_TAB: [Array] } ],
        TEXTDATA:
          [ { SPRAS: 'R',
            FIELDNAME: 'CARD_DESCRIPTION',
            TDFORMAT: '',
            TDLINE: 'ПРОПУСК' } ],
        APPRDATA:
          [ { FROMTEMPL: '',
            EXPRESS: '',
            APRST: '1',
            WI_ID: '000000000000',
            APPR_TMPL_ID: '',
            MANUALLY_ADD: '',
            SOFM_NOTE: '',
            PROC_USER: '',
            FIRST_PROC_DATE: '00000000',
            FIRST_PROC_TIME: '000000',
            PROC_DATE: '00000000',
            PROC_TIME: '000000',
            PROC_NAME_FULL: '',
            CREATED_BY: 'OGOREL_SV',
            CREATED_ON: '20181005',
            CREATED_TM: '133241',
            CREATED_BY_NAME: 'Сергей Владимирович Огорелышев',
            APRROLE: 'AU',
            APRTYPE: 'P',
            APRNAME: '11075104',
            BEGDATA: '00000000',
            BEGTIME: '000000',
            ENDDATA: '00000000',
            ENDTIME: '000000',
            APRNAME_FULL: 'Крижевских Оксана Сергеевна',
            APPRQUEUE: '00',
            APPRDAYS: '00',
            APPRHOURS: '000',
            PARENTAPRNR: '0000',
            SOFM_TASK: '',
            XDNUM: '' },
          { FROMTEMPL: '',
            EXPRESS: '',
            APRST: '1',
            WI_ID: '000000000000',
            APPR_TMPL_ID: '',
            MANUALLY_ADD: '',
            SOFM_NOTE: '',
            PROC_USER: '',
            FIRST_PROC_DATE: '20181005',
            FIRST_PROC_TIME: '133238',
            PROC_DATE: '00000000',
            PROC_TIME: '000000',
            PROC_NAME_FULL: '',
            CREATED_BY: 'OGOREL_SV',
            CREATED_ON: '20181005',
            CREATED_TM: '133241',
            CREATED_BY_NAME: 'Сергей Владимирович Огорелышев',
            APRROLE: 'IN',
            APRTYPE: 'P',
            APRNAME: '11098751',
            BEGDATA: '00000000',
            BEGTIME: '000000',
            ENDDATA: '00000000',
            ENDTIME: '000000',
            APRNAME_FULL: 'Огорелышев Сергей Владимирович',
            APPRQUEUE: '00',
            APPRDAYS: '00',
            APPRHOURS: '000',
            PARENTAPRNR: '0000',
            SOFM_TASK: '',
            XDNUM: '' },
          { FROMTEMPL: '',
            EXPRESS: '',
            APRST: 'P',
            WI_ID: '000000000000',
            APPR_TMPL_ID: '',
            MANUALLY_ADD: '',
            SOFM_NOTE: '',
            PROC_USER: '',
            FIRST_PROC_DATE: '00000000',
            FIRST_PROC_TIME: '000000',
            PROC_DATE: '00000000',
            PROC_TIME: '000000',
            PROC_NAME_FULL: '',
            CREATED_BY: 'OGOREL_SV',
            CREATED_ON: '20181005',
            CREATED_TM: '133241',
            CREATED_BY_NAME: 'Сергей Владимирович Огорелышев',
            APRROLE: 'IW',
            APRTYPE: 'P',
            APRNAME: '11098751',
            BEGDATA: '00000000',
            BEGTIME: '000000',
            ENDDATA: '00000000',
            ENDTIME: '000000',
            APRNAME_FULL: 'Огорелышев Сергей Владимирович',
            APPRQUEUE: '00',
            APPRDAYS: '00',
            APPRHOURS: '000',
            PARENTAPRNR: '0000',
            SOFM_TASK: '',
            XDNUM: '' },
          { FROMTEMPL: '',
            EXPRESS: '',
            APRST: 'S',
            WI_ID: '000000000000',
            APPR_TMPL_ID: '',
            MANUALLY_ADD: '',
            SOFM_NOTE: '',
            PROC_USER: '',
            FIRST_PROC_DATE: '00000000',
            FIRST_PROC_TIME: '000000',
            PROC_DATE: '00000000',
            PROC_TIME: '000000',
            PROC_NAME_FULL: '',
            CREATED_BY: 'OGOREL_SV',
            CREATED_ON: '20181005',
            CREATED_TM: '133241',
            CREATED_BY_NAME: 'Сергей Владимирович Огорелышев',
            APRROLE: 'MT',
            APRTYPE: 'ZK',
            APRNAME: '11002',
            BEGDATA: '00000000',
            BEGTIME: '000000',
            ENDDATA: '00000000',
            ENDTIME: '000000',
            APRNAME_FULL: 'КПП №7 ЦЕНТРАЛЬНАЯ ПРОХОДНАЯ',
            APPRQUEUE: '00',
            APPRDAYS: '00',
            APPRHOURS: '000',
            PARENTAPRNR: '0000',
            SOFM_TASK: '',
            XDNUM: '' },
          { FROMTEMPL: '',
            EXPRESS: '',
            APRST: '1',
            WI_ID: '000000000000',
            APPR_TMPL_ID: '',
            MANUALLY_ADD: '',
            SOFM_NOTE: '',
            PROC_USER: '',
            FIRST_PROC_DATE: '20181005',
            FIRST_PROC_TIME: '152149',
            PROC_DATE: '00000000',
            PROC_TIME: '000000',
            PROC_NAME_FULL: '',
            CREATED_BY: 'SUDAKOV_AB',
            CREATED_ON: '20181005',
            CREATED_TM: '152156',
            CREATED_BY_NAME: 'Алексей Борисович Судаков',
            APRROLE: 'AG',
            APRTYPE: 'P',
            APRNAME: '11053856',
            BEGDATA: '20181005',
            BEGTIME: '000000',
            ENDDATA: '20181008',
            ENDTIME: '000000',
            APRNAME_FULL: 'Судаков Алексей Борисович',
            APPRQUEUE: '01',
            APPRDAYS: '00',
            APPRHOURS: '000',
            PARENTAPRNR: '0000',
            SOFM_TASK: '',
            XDNUM: '' } ],
        ACTIONS:
          [ { ACTION: 'IN', DESCRIPTION: 'Отметить вход' },
            { ACTION: 'RET', DESCRIPTION: 'На доработку' } ]
      }]
    }
  },
  async mounted () {
    this.card.push((await axios.get(`${this.$config.api}/bydoknr?doknr=${doknr}&kpp=${kpp}`)).data)
  }
}</script>

<style scoped>

</style>
